const dummyData = [
  //streetfood
  {
    food_id: 301,
    name: "떡볶이",
    category: ["kr", "streetfood", "night"],
    calorie: 280,
    average_price: 5000,
    image:
      "https://kr.freepik.com/free-photo/cheesy-tokbokki-korean-traditional-food-black-board-background-lunch-dish_13902862.htm#fromView=search&page=1&position=0&uuid=d8985f1c-da7c-4d04-bcef-86c5758736ce",
    likes: 0,
  },
  {
    food_id: 302,
    name: "라면",
    category: ["kr", "streetfood", "night"],
    calorie: 385,
    average_price: 3000,
    image: "https://pixabay.com/ko/photos/%EB%9D%BC%EB%A9%B4-%EA%B5%AD%EC%88%98-%EC%A0%91%EC%8B%9C-%EC%9D%8C%EC%8B%9D-5579023/",
    likes: 0,
  },
  {
    food_id: 303,
    name: "김밥",
    category: ["kr", "streetfood"],
    calorie: 147,
    average_price: 4000,
    image:
      "https://kr.freepik.com/free-photo/korean-food-kim-bap-steamed-rice-with-vegetables-seaweed_13902822.htm#fromView=search&page=1&position=7&uuid=cb4882a6-5203-48ba-ad65-0e824c9cae0c",
    likes: 0,
  },
  {
    food_id: 304,
    name: "라볶이",
    category: ["kr", "streetfood"],
    calorie: 417,
    average_price: 6000,
    image:
      "https://kr.freepik.com/premium-photo/geuleus-e-damgin-hangug-bunsig-eumsig-labokk-i-yoli_49130632.htm#fromView=search&page=1&position=8&uuid=886e9fd9-2e91-4b54-ba45-5a463d166ebd",
    likes: 0,
  },
  {
    food_id: 305,
    name: "칼국수",
    category: ["kr", "streetfood"],
    calorie: 420,
    average_price: 9500,
    image:
      "https://pixabay.com/ko/photos/%EC%B9%BC%EA%B5%AD%EC%88%98-%EB%A7%A4%EC%9A%B4%EC%B9%BC%EA%B5%AD%EC%88%98-%EB%B0%94%EC%A7%80%EB%9D%BD%EC%B9%BC%EA%B5%AD%EC%88%98-3029172/",
    likes: 0,
  },
  {
    food_id: 306,
    name: "돈가스",
    category: ["jp", "streetfood"],
    calorie: "568",
    average_price: 10500,
    image: "https://pixabay.com/ko/photos/%EB%8F%88%EA%B9%8C%EC%8A%A4-%EC%9D%8C%EC%8B%9D-%EC%B9%98%EC%A6%88-%EB%8F%88%EA%B9%8C%EC%8A%A4-7593904/",
    likes: 0,
  },
  {
    food_id: 307,
    name: "우동",
    category: ["jp", "streetfood"],
    calorie: 404,
    average_price: 7000,
    image: "",
    likes: 0,
  },
  {
    food_id: 308,
    name: "오므라이스",
    category: ["us", "streetfood"],
    calorie: 380,
    average_price: 9000,
    image: "",
    likes: 0,
  },
  {
    food_id: 309,
    name: "쫄면",
    category: ["kr", "streetfood"],
    calorie: 211,
    average_price: 9500,
    image: "",
    likes: 0,
  },
  {
    food_id: 310,
    name: "떡국",
    category: ["kr", "streetfood"],
    calorie: 345,
    average_price: 9500,
    image: "",
    likes: 0,
  },
  {
    food_id: 311,
    name: "덮밥",
    category: ["kr", "jp", "streetfood"],
    calorie: 440,
    average_price: 9500,
    image: "",
    likes: 0,
  },
  {
    food_id: 312,
    name: "볶음밥",
    category: ["kr", "us", "streetfood"],
    calorie: 333,
    average_price: 9500,
    image: "https://pixabay.com/ko/photos/%EA%B9%80%EC%B9%98-%EB%B3%B6%EC%9D%8C%EB%B0%A5-%EB%B3%B6%EC%9D%8C%EB%B0%A5-%EC%8C%80-241051/",
    likes: 0,
  },
  {
    food_id: 313,
    name: "냉면",
    category: ["kr", "streetfood"],
    calorie: 383,
    average_price: 9500,
    image: "",
    likes: 0,
  },
  {
    food_id: "314",
    name: "토스트",
    category: ["us", "streetfood"],
    calorie: 420,
    average_price: 5000,
    image: "",
    likes: 0,
  },
  {
    food_id: 315,
    name: "순대",
    category: ["kr", "streetfood"],
    calorie: 269,
    average_price: 5000,
    image: "",
    likes: 0,
  },
  {
    food_id: 316,
    name: "닭강정",
    category: ["kr", "streetfood", "night"],
    calorie: 663,
    average_price: 9500,
    image: "",
    likes: 0,
  },
  {
    food_id: 317,
    name: "만두",
    category: ["kr", "cn", "streetfood"],
    calorie: 203,
    average_price: 10000,
    image: "",
    likes: 0,
  },
  {
    food_id: 319,
    name: "비빔밥",
    category: ["kr", "streetfood"],
    calorie: 586,
    average_price: 9000,
    image: "",
    likes: 0,
  },
  //-------------------------------------
  //us
  {
    food_id: 321,
    name: "파스타",
    category: ["us"],
    calorie: 275,
    average_price: 10000,
    image: "",
    likes: 0,
  },
  {
    food_id: 322,
    name: "피자",
    category: ["us", "night"],
    calorie: 511,
    average_price: 25000,
    image: "",
    likes: 0,
  },
  {
    food_id: 323,
    name: "스테이크",
    category: ["us", "고기구이"],
    calorie: 214,
    average_price: 20000,
    image: "",
    likes: 0,
  },
  {
    food_id: 324,
    name: "샐러드",
    category: ["us"],
    calorie: 184,
    average_price: 10000,
    image: "",
    likes: 0,
  },
  {
    food_id: 325,
    name: "리조또",
    category: ["us"],
    calorie: 311,
    average_price: 13000,
    image: "",
    likes: 0,
  },
  {
    food_id: 326,
    name: "햄버거",
    category: ["us", "night"],
    calorie: 426,
    average_price: 8000,
    image: "",
    likes: 0,
  },
  {
    food_id: 327,
    name: "뇨끼",
    category: ["us"],
    calorie: 355,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 328,
    name: "라자냐",
    category: ["us"],
    calorie: 370,
    average_price: 10000,
    image: "",
    likes: 0,
  },
  {
    food_id: 329,
    name: "타코",
    category: ["us"],
    calorie: 304,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 330,
    name: "브리또",
    category: ["us"],
    calorie: 325,
    average_price: 6000,
    image: "",
    likes: 0,
  },
  {
    food_id: 331,
    name: "퀘사디아",
    category: ["us"],
    calorie: 485,
    average_price: 15000,
    image: "",
    likes: 0,
  },

  //--------------------------------------
  //asia
  {
    food_id: 341,
    name: "쌀국수",
    category: ["asia"],
    calorie: 320,
    average_price: 10000,
    image: "",
    likes: 0,
  },
  {
    food_id: 342,
    name: "커리",
    category: ["asia"],
    calorie: 279,
    average_price: 13000,
    image: "",
    likes: 0,
  },
  {
    food_id: 343,
    name: "분짜",
    category: ["asia"],
    calorie: 640,
    average_price: 13000,
    image: "",
    likes: 0,
  },
  {
    food_id: 344,
    name: "똠얌꿍",
    category: ["asia"],
    calorie: 196,
    average_price: 13000,
    image: "",
    likes: 0,
  },
  {
    food_id: 345,
    name: "반쎄오",
    category: ["asia"],
    calorie: 687,
    average_price: 8000,
    image: "",
    likes: 0,
  },
  {
    food_id: 346,
    name: "팟타이",
    category: ["asia"],
    calorie: 340,
    average_price: 10000,
    image: "",
    likes: 0,
  },
  {
    food_id: 347,
    name: "반미",
    category: ["asia"],
    calorie: 386,
    average_price: 8000,
    image: "",
    likes: 0,
  },
  {
    food_id: 348,
    name: "나시고랭",
    category: ["asia"],
    calorie: 346,
    average_price: 10000,
    image: "",
    likes: 0,
  },
  //---------------------------------------------
  //night
  {
    food_id: 351,
    name: "낙곱새",
    category: ["kr", "night"],
    calorie: 240,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 352,
    name: "마라탕",
    category: ["cn", "night"],
    calorie: 175,
    average_price: 13000,
    image: "",
    likes: 0,
  },
  {
    food_id: 353,
    name: "막창",
    category: ["고기구이", "night"],
    calorie: 601,
    average_price: 20000,
    image: "",
    likes: 0,
  },
  {
    food_id: 354,
    name: "해물찜",
    category: ["kr", "night"],
    calorie: 269,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 355,
    name: "족발",
    category: ["kr", "night"],
    calorie: 458,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 356,
    name: "닭발",
    category: ["kr", "night"],
    calorie: 243,
    average_price: 13000,
    image: "",
    likes: 0,
  },
  {
    food_id: 357,
    name: "치킨",
    category: ["kr", "us", "night"],
    calorie: 750,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 358,
    name: "곱창",
    category: ["kr", "고기구이", "night"],
    calorie: 268,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 359,
    name: "보쌈",
    category: ["kr", "night"],
    calorie: 581,
    average_price: 15000,
    image: "",
    likes: 0,
  },
  {
    food_id: 360,
    name: "양꼬치",
    category: ["cn", "night"],
    calorie: 260,
    average_price: 15000,
    image: "",
    likes: 0,
  },
];
