"use client";

import localFont from "next/font/local";
import "./globals.css";
import GlobalLayout from "@/components/GlobalLayout/global-layout";
import { UserProvider } from "@/context/userContext";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const metadata = {
  title: "TodayEat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProvider>
          <UserProvider>
            <GlobalLayout>{children}</GlobalLayout>
          </UserProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
